### ISSUE TITLE
filter 參數沒有作用？

### ISSUE THREAD

**Issue by vacarogit** [zhongjiajie/beauty#1]
@-iMac
$beauty download xiuren **-n 1 -f [207558]**
finish download album 207752_[秀人·魅妍社]性感兔女郎小热巴酥胸美腿诱惑写真 downloading NO.41 picture
@-iMac

filter 參數沒有作用？

**Comment by zhongjiajie** [comment]
@vacarogit  抱歉这么晚才给回复,我这我这边试了一下发现没有问题,我的代码如下
```python
beauty download xiuren -n 10 -f '[207744,207751]'
```
![runed_screenshots](http://plevc3p2c.bkt.clouddn.com/beauty_runed_result.png)
我一开始的时候使用`beauty download xiuren -n 10 -f [207744,207751]`在ubuntu下发现报错,就在`'[207744,207751]'`参数加了引号,就能成功运行了,如果你是用*unix环境的话也要加引号

**Comment by zhongjiajie** [comment]
@vacarogit 如果没有问题我就关issue了,遇到问题再讨论.
近期打算重写项目,如果有人感兴趣可以参加,打算写个页面访问
